sculpin:
    ignore: ["**/*.scss"]

sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
        taxonomies:
            - tags
            - categories
            - authors

    jobs:
        permalink: jobs/:slug_title/
        path: _jobs
        singular_name: job
        layout: job
        enabled: true

symbid_authors:
    authors:
        mennovanslooten:
          name: Menno van Slooten
          url: http://mennovanslooten.nl
          avatar: https://pbs.twimg.com/profile_images/1752009279/headshot.png
          twitter: http://twitter.com/mennovanslooten
          twitter_handle: mennovanslooten
          github: https://github.com/mennovanslooten
          email: menno@symbid.com
          linkedin: http://nl.linkedin.com/in/mennovanslooten
          bio: Symbid's Lead Guitarist and Frontend developer.
        rdohms:
          name: Rafael Dohms
          url: http://doh.ms
          avatar: https://pbs.twimg.com/profile_images/2619935061/wzdfd5co5z0a242piele_400x400.jpeg
          twitter: http://twitter.com/rdohms
          twitter_handle: rdohms
          github: https://github.com/rdohms
          email: rafael@symbid.com
          linkedin: http://nl.linkedin.com/in/rafaeldohms
          bio: Symbid's Lead Backend Developer. Serial Creator of User Groups, speaker and contributor to PHP and its ecosystem.
